// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsEJkg8f1WHCtVWIaB0F3BzdZqNDtPAxo',
    appId: '1:703131294804:web:040b1f92b6261971dd21c1',
    messagingSenderId: '703131294804',
    projectId: 'fir-flutter-codelab-7a4b8',
    authDomain: 'fir-flutter-codelab-7a4b8.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-7a4b8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTuDZU_0B0hwZbSYm3HLt3rnRA8h6SbHo',
    appId: '1:703131294804:android:da1ec9fbbb5307f3dd21c1',
    messagingSenderId: '703131294804',
    projectId: 'fir-flutter-codelab-7a4b8',
    storageBucket: 'fir-flutter-codelab-7a4b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsc-rSjIxw1n252mcshYqvL7piwJnqTQo',
    appId: '1:703131294804:ios:38b9ba890d46d28edd21c1',
    messagingSenderId: '703131294804',
    projectId: 'fir-flutter-codelab-7a4b8',
    storageBucket: 'fir-flutter-codelab-7a4b8.appspot.com',
    iosClientId: '703131294804-lq0vpmcuv4f36558rmieqv6fe5e0q1o6.apps.googleusercontent.com',
    iosBundleId: 'com.example.start',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsc-rSjIxw1n252mcshYqvL7piwJnqTQo',
    appId: '1:703131294804:ios:38b9ba890d46d28edd21c1',
    messagingSenderId: '703131294804',
    projectId: 'fir-flutter-codelab-7a4b8',
    storageBucket: 'fir-flutter-codelab-7a4b8.appspot.com',
    iosClientId: '703131294804-lq0vpmcuv4f36558rmieqv6fe5e0q1o6.apps.googleusercontent.com',
    iosBundleId: 'com.example.start',
  );
}
